## Statistical Calculations

In [2]:
import numpy as np

In [3]:
v=np.array([1,1,2,2,3,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3, 3])

In [4]:
v.mean()

2.25

In [6]:
np.median(v)

2.5

In [8]:
np.median(v)

2.5

In [9]:
v.sum()

18

In [10]:
v.min()

1

In [ ]:
np.mean(v)

## A sample Solve In Linear Algebra Using Numpy

In [13]:
a = np.array([[3, 1], [1, 2]])
b = np. array([9,8])

In [14]:
a

array([[3, 1],
       [1, 2]])

In [15]:
b

array([9, 8])

In [16]:
np.linalg.solve(a,b)

array([2., 3.])