In [ ]:
data = [1,2,3]
data2 = data[::-1]
result = []
for i in range(len(data)):
    result.append(data[i:]+data[:i])
    result.append(data2[i:]+data2[:i])
    
result

[[1, 2, 3], [3, 2, 1], [2, 3, 1], [2, 1, 3], [3, 1, 2], [1, 3, 2]]

In [ ]:
x = []
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
for i in list1:
  if i <= 150 and i % 5 == 0 :
    x.append(i)
x
  


[15, 55, 75, 150]

In [ ]:
toplam = 0
liste = [20,100,1000,10156,50,60,852,9000]
for i in liste:
   if len(str(i)) > 3:
     toplam += i
print(toplam)

20156


In [ ]:
sum([i for i in liste if len(str(i)) >3])

20156

In [ ]:
x = 1,2,3,4,5
for i in range (5,0,-1):
  for j in range(i,0,-1):
    print(j, end = " ")
  print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [ ]:
list1 = [10, 20, 30, 40, 50]
for i in list1:
  print(list1[::-1])

[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]
[50, 40, 30, 20, 10]


In [ ]:
for i in range(5):
    print(i)
else:
    print(i)

0
1
2
3
4
4


In [ ]:
start = 25
end = 50
for i in range(25,50):
  for j in range(2,i) : 
    if i%j == 0:
      break
  else :
    print(f"{i} is prime number") 


29 is prime number
31 is prime number
37 is prime number
41 is prime number
43 is prime number
47 is prime number


In [ ]:
a ,b = 0,1
count = 0
while count < 15:
  print(a, end= " ")
  a, b = b, a+b
  count += 1 


0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 

In [ ]:
a = 76542
for i in str(a) :
  print(a(-1))


TypeError: ignored

In [ ]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
a=[i for i in my_list[0:len(my_list):2]]
a

[10, 30, 50, 70, 90]

In [2]:
import numpy as np

In [ ]:
a = [1, 3, 5, 7]
b = [2, 4 ,6, 8]
c = [3, 6, 9,12]
a = np.array(a)
a = np.array(a)
b = np.array(b)
c = np.array(c)
d = a*b*c
d = list(d)
print(d)

[6, 72, 270, 672]


In [ ]:
d = np.array([3.14,14,15,16])
type(d)
d.dtype


dtype('float64')

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [5]:
 np.arange(4,20).reshape(4,4)             

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.random.randint(3,9, size = (3,8))

array([[3, 3, 8, 7, 3, 8, 4, 7],
       [3, 4, 8, 4, 6, 4, 6, 7],
       [5, 6, 5, 4, 5, 7, 8, 5]])

In [ ]:
a = np.arange(1,16,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
a.reshape(2,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [6]:
#concatenate
a= np.random.randint(1,6, size=9)
b= np.random.randint(2,7, size=9)
c = np.concatenate([a,b])
c

array([4, 5, 4, 1, 1, 2, 3, 5, 4, 4, 2, 3, 2, 5, 2, 2, 5, 3])

In [13]:
a= np.random.randint(2,7, size=(3,4))
b= np.random.randint(8,14, size=(3,4))
c= np.concatenate([a,b], axis =0)
c

array([[ 4,  6,  2,  6],
       [ 6,  5,  2,  2],
       [ 6,  5,  5,  4],
       [ 9, 11, 11,  8],
       [ 9,  9,  8,  9],
       [ 8,  9, 13, 13]])

In [15]:
c=np.concatenate([a,b], axis=1)
c

array([[ 4,  6,  2,  6,  9, 11, 11,  8],
       [ 6,  5,  2,  2,  9,  9,  8,  9],
       [ 6,  5,  5,  4,  8,  9, 13, 13]])

In [17]:
c

array([[ 4,  6,  2,  6,  9, 11, 11,  8],
       [ 6,  5,  2,  2,  9,  9,  8,  9],
       [ 6,  5,  5,  4,  8,  9, 13, 13]])

In [16]:
c.ndim

2

In [ ]:
c.size

24

In [ ]:
c.shape

(3, 8)

In [ ]:
c.mean()

7.25

In [ ]:
c.std()

3.3942353090693835

In [ ]:
c.var()

11.520833333333334

In [ ]:
np.sort(c)

array([[ 3,  5,  5,  5,  8, 10, 12, 13],
       [ 2,  4,  5,  6,  9,  9, 10, 11],
       [ 3,  3,  4,  5,  8, 10, 11, 13]])

In [18]:
c

array([[ 4,  6,  2,  6,  9, 11, 11,  8],
       [ 6,  5,  2,  2,  9,  9,  8,  9],
       [ 6,  5,  5,  4,  8,  9, 13, 13]])

In [20]:
np.sort(c, axis=0)

array([[ 4,  5,  2,  2,  8,  9,  8,  8],
       [ 6,  5,  2,  4,  9,  9, 11,  9],
       [ 6,  6,  5,  6,  9, 11, 13, 13]])

In [24]:
c=np.concatenate([a,b], axis=0)
c

array([[ 4,  6,  2,  6],
       [ 6,  5,  2,  2],
       [ 6,  5,  5,  4],
       [ 9, 11, 11,  8],
       [ 9,  9,  8,  9],
       [ 8,  9, 13, 13]])

In [27]:
np.sort(c, axis=1)

array([[ 2,  4,  6,  6],
       [ 2,  2,  5,  6],
       [ 4,  5,  5,  6],
       [ 8,  9, 11, 11],
       [ 8,  9,  9,  9],
       [ 8,  9, 13, 13]])

In [ ]:
 a

array([[5, 5, 5, 3],
       [5, 4, 2, 6],
       [3, 3, 4, 5]])

In [ ]:
a[0]

array([5, 5, 5, 3])

In [ ]:
a[1]

array([5, 4, 2, 6])

In [ ]:
a[2]

array([3, 3, 4, 5])

In [ ]:
a[-1]

array([3, 3, 4, 5])

In [ ]:
a[1,1]

4

In [28]:
a

array([[4, 6, 2, 6],
       [6, 5, 2, 2],
       [6, 5, 5, 4]])

In [30]:
a[0:3,2]

array([2, 2, 5])

In [31]:
a[0:2,0:3]

array([[4, 6, 2],
       [6, 5, 2]])

In [ ]:
c

array([[ 5,  5,  5,  3, 10, 12, 13,  8],
       [ 5,  4,  2,  6,  9,  9, 11, 10],
       [ 3,  3,  4,  5,  8, 13, 10, 11]])

In [ ]:
c>8

array([[False, False, False, False,  True,  True,  True, False],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True]])

In [ ]:
c[c>8]

array([10, 12, 13,  9,  9, 11, 10, 13, 10, 11])

In [ ]:
len(c[c>8])

10

In [ ]:
c[0:2]>7 # > isareti parantez dışı ise boolean döner

array([[False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True]])

In [33]:
import seaborn as sb


In [38]:
sb.load_dataset("planets")

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [ ]:
sb.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [44]:
df = sb.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [45]:
a 

array([[4, 6, 2, 6],
       [6, 5, 2, 2],
       [6, 5, 5, 4]])

In [47]:
np.add(a,13) # add fonksiyonu a dan sonra yazdığımız veriyle a nın değerlerini topluyor

array([[17, 19, 15, 19],
       [19, 18, 15, 15],
       [19, 18, 18, 17]])

In [48]:
np.subtract(a,5)

array([[-1,  1, -3,  1],
       [ 1,  0, -3, -3],
       [ 1,  0,  0, -1]])

In [49]:
np.multiply(a,3)

array([[12, 18,  6, 18],
       [18, 15,  6,  6],
       [18, 15, 15, 12]])

In [50]:
np.divide(a,2)

array([[2. , 3. , 1. , 3. ],
       [3. , 2.5, 1. , 1. ],
       [3. , 2.5, 2.5, 2. ]])

In [52]:
a

array([[4, 6, 2, 6],
       [6, 5, 2, 2],
       [6, 5, 5, 4]])

In [55]:
np.mod(a,3) # python daki % ile aynı

array([[1, 0, 2, 0],
       [0, 2, 2, 2],
       [0, 2, 2, 1]], dtype=int32)

In [58]:
np.absolute(a)  # mutlak değer

array([[4, 6, 2, 6],
       [6, 5, 2, 2],
       [6, 5, 5, 4]])

In [59]:
np.cos(a[1])

array([ 0.96017029,  0.28366219, -0.41614684, -0.41614684])

In [60]:
np.sin(a[2])

array([-0.2794155 , -0.95892427, -0.95892427, -0.7568025 ])

In [61]:
np.tan(a)

array([[ 1.15782128, -0.29100619, -2.18503986, -0.29100619],
       [-0.29100619, -3.38051501, -2.18503986, -2.18503986],
       [-0.29100619, -3.38051501, -3.38051501,  1.15782128]])

In [62]:
a

array([[4, 6, 2, 6],
       [6, 5, 2, 2],
       [6, 5, 5, 4]])

In [63]:
np.log(2)

0.6931471805599453

In [ ]:
np.log(a[1,2])

0.6931471805599453

In [ ]:
np.log10(a[1])

array([0.69897   , 0.60205999, 0.30103   , 0.77815125])

In [ ]:
np.sqrt(16)

4.0

In [64]:
np.power(5,2)

25

In [65]:
np.power(a,2)

array([[16, 36,  4, 36],
       [36, 25,  4,  4],
       [36, 25, 25, 16]], dtype=int32)

In [66]:
np.square(a) # square ile sqrt ters

array([[16, 36,  4, 36],
       [36, 25,  4,  4],
       [36, 25, 25, 16]], dtype=int32)

In [67]:
a = np.arange(2,10).reshape(4,2)
a

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
print(" Array shape is: " ,a.shape)


 Array shape is:  (4, 2)


In [ ]:
print(" Dimensions is: " ,a.ndim)

 Dimensions is:  2


In [ ]:
print(" Array number of element is: " ,a.size)

 Array number of element is:  8


In [ ]:
print(" Array byte is: " , a.itemsize)

 Array number of element is:  8


In [91]:
a=np.array([5,7], dtype="S")

In [92]:
a.dtype

dtype('S1')

In [ ]:
a = np.arange(100,200, 10,).reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [94]:
a = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
a

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [95]:
a[...,2]

array([33, 66, 99])

In [96]:
a[::,2]

array([33, 66, 99])

In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [ ]:
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [ ]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
c = arrayOne+arrayTwo
np.square(c)
          

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [99]:
a = np.arange(10,34).reshape(8,3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [100]:
a = np.arange(10,34).reshape(8,3)
np.split(a,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [103]:
a = np.array([[34,43,73],[82,22,12],[53,94,66]])

a[1]=np.sort(a[1])
a

array([[34, 43, 73],
       [12, 22, 82],
       [53, 94, 66]])

In [2]:
import numpy as np
import pandas as pd
num1=np.random.randint(1,20,size=(3,6))
num2=np.random.randint(1,20,size=(3,5))
num3=np.concatenate((num1,num2),axis=1)
df=pd.DataFrame(num3, index=["satir satir2 satir3".split()], columns=[list("abcdefghjkl")])
df

a   b   c   d   e  f   g   h   j  k   l
satir   5  19  14  17  16  9  12  17   1  6  18
satir2  7   8   7   4   3  2  13  11  13  2  12
satir3  3  17   9  11   2  8  15  11  16  8   7

In [3]:
df.iloc[1,2]

7

In [5]:
df.loc["satir","c"]

c
satir  14

In [6]:
df

a   b   c   d   e  f   g   h   j  k   l
satir   5  19  14  17  16  9  12  17   1  6  18
satir2  7   8   7   4   3  2  13  11  13  2  12
satir3  3  17   9  11   2  8  15  11  16  8   7

In [8]:
df.drop("satir")

a   b  c   d  e  f   g   h   j  k   l
satir2  7   8  7   4  3  2  13  11  13  2  12
satir3  3  17  9  11  2  8  15  11  16  8   7

In [9]:
df.drop("h", axis=1)

a   b   c   d   e  f   g   j  k   l
satir   5  19  14  17  16  9  12   1  6  18
satir2  7   8   7   4   3  2  13  13  2  12
satir3  3  17   9  11   2  8  15  16  8   7